name: CI
on: 
  workflow_dispatch: 
     inputs:
        environment:
          description: "dynamic image tag"
          required: true
          default: "latest"
          
jobs:
  first-job:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v4
      - name: Printing Greeting
        run: echo Hello World
      - name: Image tagging
        run: |
            IMAGE_TAG ="${{ github.event.inputs.environment }}"
            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=\"$IMAGE_TAG\"/" script.sh
            bash script.sh
            
