name: First-Workflow
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
jobs:
  first-job:
    runs-on: ubuntu_latest
    steps:
      #- uses: actions/checkout@v4
      - name: Printing Greeting
        run: echo "Hello World"
      - name: Printing Goodbye
        run: echo "Goodbye!!"
