---
name: Scheduled Netlify site build
on:
  workflow_dispatch:
permissions: {} # none
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Trigger build on Netlify
      env:
        TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK_KEY }}
      run: >-
          curl -s -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d "{}" "https://api.netlify.com/build_hooks/${TOKEN}"
